const cosmeticos= [
    { id: "1", nombre: "Labial Studio Look Mate", descripcion: "El favorito de todas. Labial líquido Studio Look mate de larga duración, un must-have para combinar todos tus looks. 6ml / 0.17fl.oz.", imagen: "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200103920_fotofondoblanco.jpg", color: "LATTE", precio: 109.9, stock: 30, categoria: "labial"},
    { id: "2", nombre: "spray fijador maquillaje studio look", descripcion: "makeup intacto. el spray fijador hará que tu maquillaje dure por más tiempo además de brindarle un acabado mate a tu rostro. 60ml/2.04 fl.oz", imagen: "https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200102371_fotofondoblanco.jpg", color: "Transparente", precio: 169.9, stock: 15, categoria: "otros"},
    { id: "3", nombre: "Delineador Plumón Studio Look Para Ojos", descripcion: "Delineado perfecto. Delineador Plumón Studio Look Para Ojos de alta precisión, color negro intenso y fácil aplicación. 1ml.", imagen: "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/210095652_fotofondoblanco.jpg", color: "Negro", precio: 109.9 , stock: 6, categoria: "delineador"},
    { id: "4", nombre: "Labial Graduable Mate Studio Look", descripcion: "¡Tú decides la intensidad! Labial en barra con acabado mate de textura ultra ligera 2g.", imagen: "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200098797_fotofondoblanco.jpg", color: "Blush nude", precio: 109.98, stock: 10, categoria: "labial"},
    { id: "5", nombre: "Delineador De Cejas Plumón 2 En 1 Wow Brow Studio Look", descripcion: "Cejas naturales contigo todo el día. Delineador De Cejas Plumón 2 En 1 Wow Brow Studio Look de larga duración con efecto microblading 0.6 ml.", imagen: "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/210097511_fotofondoblanco.jpg", color: "Dark Brown", precio: 154.9, stock: 4, categoria: "delineador"},
    { id: "6", nombre: "Paleta Para Rostro Studio Look", descripcion: "5 productos, 1 paleta. La Paleta Para Rostro Studio Look 5 en 1 es la más completa para resaltar, definir, broncear, dar color e iluminar tu rostro.", imagen: "https://cyzone.tiendabelcorp.com/cdn-cgi/image/width=1200,fit=contain,f=auto/https://belc-bigdata-mdm-images-prd.s3.amazonaws.com/images/FotoProductoFondoBlancoWebRedes/200102276_fotofondoblanco.jpg", color: "Calidos", precio: 229.9, stock: 33, categoria: "paleta"}
]

export default cosmeticos